spring.application.name=trivia-backend

#H2 Database
spring.datasource.url=jdbc:h2:file:./data/triviadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

server.error.include-message=always

jwt.secret=ThisIsMyVeryLongDevelopmentSecretKey1234567890
jwt.expiration=3600000

logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE
